import Head from 'next/head';

// Components
import Banner from '@/components/common/Banner';
import CallToAction from '@/components/callToAction/CallToAction';
import Menu from '@/components/menu/Menu';
import Employee from '@/components/employee/Employee';
import Layout from '@/components/layout/Layout';
import { ReactNode } from 'react';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<>
				<Banner />
				<CallToAction />
				<Menu />
				<Employee />
			</>
		</>
	);
}

Home.getLayout = function getLayout(page: ReactNode) {
	return <Layout>{page}</Layout>;
};
