import Head from 'next/head';
import Image from 'next/image';
import localFont from 'next/font/local';
import styles from '@/styles/Home.module.css';

// Components
import Banner from '@/components/common/Banner';
import CallToAction from '@/components/callToAction/CallToAction';
import Menu from '@/components/menu/Menu';
import Employee from '@/components/employee/Employee';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<>
				<Banner />
				<CallToAction />
				<Menu />
				<Employee />
			</>
		</>
	);
}
